version: '3.8'

services:
  backend:
    build:
      context: .
      target: backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/backend
    volumes:
      - ./backend:/app/backend
    networks:
      - ai-chat-network

  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
    volumes:
      - ./frontend/src:/app/frontend/src
    networks:
      - ai-chat-network
    depends_on:
      - backend

networks:
  ai-chat-network:
    driver: bridge
