#!/bin/bash

echo "🎲 Probability Dashboard Demo"
echo "=============================="
echo ""
echo "The dashboard is now running at: http://localhost:5000"
echo ""
echo "📊 Dashboard Features:"
echo "  🪙 Coin Flip Simulation - Watch probability converge to 0.5"
echo "  🎲 Die Roll Distribution - See uniform distribution in action"
echo "  📧 Spam Classifier - Classify emails with confidence scores"
echo ""
echo "🔧 How to use:"
echo "  1. Open http://localhost:5000 in your browser"
echo "  2. Click 'Start Simulation' buttons to begin live updates"
echo "  3. Type emails in the classifier to see real-time results"
echo "  4. Watch charts update automatically with WebSocket data"
echo ""
echo "💡 Try these sample emails:"
echo "  - 'win free prize money' (should be classified as SPAM)"
echo "  - 'meeting about the project' (should be classified as HAM)"
echo "  - 'free lunch today' (borderline case)"
echo ""
echo "🛑 To stop the dashboard: Press Ctrl+C in the terminal"
echo ""
echo "Dashboard is ready! 🚀"
